### ISSUE TITLE
Syntax highlighting in live specification is incorrect

### ISSUE THREAD

**Issue by jakelishman** [openqasm/openqasm#369]
The syntax highlighting blocks on the OpenQASM 3 live spec site are currently not being highlighted as OpenQASM 3.  Sphinx uses Pygments as its highlighting engine, and there's currently no OpenQASM 3 support in Pygments (or in external packages), so we're currently lexing things as a mix of Python, C, and Javascript (!) and just hoping for the best.

I've written 95% of a Pygments lexer for both OpenQASM 3 and OpenPulse, which we can publish as a Python package and begin depending on.  My questions are:
- do we want this as part of the `openqasm3` package in this repo?
- do we want it within the `openqasm` organisation, or shall I host it elsewhere?

I'm happy to go with anything.  For my own view, I personally would host it as a separate repository, within this OpenQASM organisation here on GitHub.  It is really a supplemental package, and it'll be easier to manage in the long term if supplemental tooling is in separate repos.  We already do this for the `vim` syntax highlighter, and I see this as largely the same thing.

**Comment by blakejohnson** [comment]
I suggest going with your preference of a separate repository within this GitHub org.
