### ISSUE TITLE
[]: PyPI has an old version

### ISSUE THREAD

**Issue by yurivict** [openqasm/openqasm#379]
### OpenQASM version:

3.0

### Python version:

3.9

### Operating system:

FreeBSD

### What is the current behavior?

https://pypi.org/project/openqasm/ has 0.1.0  while the latest tag is 3.0

Any plans to make a new release because 3.0 was in in 2020?

### Steps to reproduce the problem

n/a

### What is the expected behavior?

n/a

### Suggested solutions (Optional)

n/a

**Comment by jwoehr** [comment]
The PyPi package in question is not an official package.
It was created another open source programmer.
The OpenQASM 3 Technical Steering Committee has been [attempting to contact the author](https://github.com/qevedo/openqasm/issues/1).
The Committee has received no response from that author, so is moving forward with the [openqasm3 package](https://pypi.org/project/openqasm3/).

**Comment by jakelishman** [comment]
This repository is primarily for defining the specification of the OpenQASM language.  It also includes a Python package that can be used to build a Python-based AST for the language ([`openqasm3`](https://pypi.org/project/openqasm3)).  These are separate things.  At the time of writing, the version of the language being worked towards is 3.0, and the version of the Python package is 0.0.1.
