### ISSUE TITLE
Please add to README how to run .qasm program files

### ISSUE THREAD

**Issue by yurivict** [openqasm/openqasm#380]
### What is the expected enhancement?

I installed OpenQASM using pip.
It only installed these 2 files:
```
%%PYTHON_SITELIBDIR%%/openqasm/__pycache__/openqasm%%PYTHON_EXT_SUFFIX%%.pyc
%%PYTHON_SITELIBDIR%%/openqasm/openqasm.py
```
and no executables.

What is the command to run .qasm files? Could you please add this information to the README?

Thanks,
Yuri

**Comment by jwoehr** [comment]
There currently is not a full reference compiler in the OpenQASM repo, just a reference _parser_.
See [my response](https://github.com/openqasm/openqasm/issues/381#issuecomment-1207132797) to #381.
