### ISSUE TITLE
Global phase of U

### ISSUE THREAD

**Issue by levbishop** [openqasm/openqasm#382]
There are 2 built-in parameterized gates, `U(θ, ϕ, λ)` and `gphase(γ)`. The definitions of these gates are explicitly 2π periodic in all the parameters except for `θ`, for which `U` is instead 4π periodic. The spec implies that `U()` is defined for  
θ in the interval [0,2π), but also says that the `inv` modifier can operate by replacing `inv @ U(θ, ϕ, λ)` by `U(-θ, -λ, -ϕ)`. Unfortunately this is not correct when considering global phase: `ctrl @ inv @ U(θ, 0, 0) c, t;` is not the same as `ctrl @ U(2pi-θ, 0, 0) c, t;` but rather needs an additional `p(pi) c;` to correct.

I can see a few options to resolve this:

1. (not preferred) redefine `U(θ, ϕ, λ)` to be equivalent to `U(θ/2, ϕ, λ)` to that all parameters can be 2pi periodic. This would be a big change to the language and i think we can discount it immediately;
5. redefine angles to overflow mod 4pi rather than mod 2pi. Pro: maintains the definition of `U` and that `inv @ U(θ, ϕ, λ)` is equivalent to `U(-θ, -λ, -ϕ)`. Pro: `U` is continuous and differentiable in all its parameters everywhere. Con: One extra bit needed to store angles. Con: a change to the behaviour of angles (although it's rarely observable and unlikely that many were relying on it)
6. clarify that indeed the θ parameter wraps mod 2pi and that therefore `inv @ U(θ, ϕ, λ)` has an extra `gphase`. Pro: minimal change to the existing spec. Con: `U` gains a discontinuity.
7. redefine the global phase of `U` so that `U(θ, ϕ, λ)` is equivalent to `exp(i(θ+ϕ+λ)/2) Rz(ϕ).Ry(θ).Rz(λ)`. We already changed the global phase going from qasm2 to qasm3, so we could have done this at the time and I wish we thought of it then. Pro: no worse relative to qasm2 than the previous definition. Pro: difference from previous definition only visible in presence of `ctrl` modifier. Pro: U gate is everywhere continuous and differentiable. Con: a difference from the previous spec version and explicit U definition in the QASM3 paper.

I think any of the options 2-4 could be acceptable but I lean towards option 4 even though its a bit embarrassing to have to revisit this and obsolete the paper.

Also, all options 2-4 only differ in the presence of `ctrl` modifier, and all can be inter-converted by judicious use of `gphase` instructions

_Originally posted by @levbishop in https://github.com/openqasm/openqasm/issues/375#issuecomment-1205410860_

**Comment by levbishop** [comment]
Decided by TSC 2022-08-19 in favour of option 4.

**Comment by blakejohnson** [comment]
Resolved by #393.
