### ISSUE TITLE
Parser does not return the right AST node for externStatement.return_type

### ISSUE THREAD

**Issue by jcjaskula-aws** [openqasm/openqasm#409]
### OpenQASM version:

3.0

### Python version:

3.9

### Operating system:

Mac

### What is the current behavior?

Parser does not correct the correct AST node when supplied an extern statement. 

### Steps to reproduce the problem

    from openqasm3.parser import parse
    parse("extern constant(int) -> bit;")
returns (Spans manually deleted)
    Program(span=None, statements=[ExternDeclaration(span=None, annotations=[], 
    name=Identifier(span=None, name='constant'), arguments=[ExternArgument(span=None, 
    type=IntType(span=None, size=None), access=None)], return_type=**BitType(span=None, size=None)**)], 
    version=None)

### What is the expected behavior?

return_type node is [expected](https://github.com/openqasm/openqasm/blob/9f0bd0b90aa848557934e11b1f880bde0d0160dd/source/openqasm/openqasm3/ast.py#L234) to be ExternArgument(type=BitType...)

**Comment by jakelishman** [comment]
That seems right? Its argument type is a single `Int` and its return is `Bit`, which seems to match your example.

**Comment by jakelishman** [comment]
Oh wait, I see what you're saying. I don't think there's any necessity for us to wrap the output in an `ExternArgument` here, since it's not an argument.

**Comment by jcjaskula-aws** [comment]
I agree. I believe changing the return_type type would be a neater solution.
