### ISSUE TITLE
Physical qubit is not scanned or parsed correctly 

### ISSUE THREAD

**Issue by jlapeyre** [openqasm/openqasm#416]
EDIT: See next comment first.

### OpenQASM version:

5858c878 , four day old main branch

### Python version:

3.10.5

### Operating system:

fedora

### What is the current behavior?

Somtimes parsing a physical qubit specification fails.

### Steps to reproduce the problem

Write the following to `phys_test.qasm`.
```
OPENQASM 3.0;

qubit $0;
```
Then do the following:
```python
In [1]: import openqasm_reference_parser

In [2]: openqasm_reference_parser.pretty_tree(file="./phys_test.qasm")
---------------------------------------------------------------------------
Qasm3ParserError                          Traceback (most recent call last)
Cell In [2], line 1
----> 1 openqasm_reference_parser.pretty_tree(file="./phys_test.qasm")

File ~/github/openqasm/openqasm/source/grammar/openqasm_reference_parser/tools.py:50, in pretty_tree(program, file)
     48     error = err.getvalue()
     49 if error:
---> 50     raise Qasm3ParserError(f"Parse tree build failed. Error:\n{error}")
     51 return tree

Qasm3ParserError: Parse tree build failed. Error:
line 3:6 mismatched input '$0' expecting Identifier
```

### What is the expected behavior?

No error. When I first read the paper it looked kind of like these should only work in a `defcal`. But there are snippets in the paper including `$0`, `$1` etc that do not explicitly include this context. The live language spec is pretty clear. There are no qualification on scope or otherwise when introducing physical qubits.

### Suggested solutions (Optional)

Reading test suite, it looks like physical qubits are parsed correctly in a `defcal`. This might be a starting point.

**Comment by jlapeyre** [comment]
This looks like I am trying to declare a physical qubit, which should not be allowed.
There is another implementation of a qasm parser which does allow this qasm code. I think the bug should be filed against that parser, not this one.

**Comment by jakelishman** [comment]
Yes, the internal IBM parser allows this as a language extension, but it's explicitly against the text of the spec.

**Comment by jakelishman** [comment]
Just to clarify: it's convenient for our infrastructure internally to know how many physical qubits will be used, which is in part why there's the syntax extension, and because our compiler assumes Qiskit has already laid out and routed the circuit, so there's no "register-like" definitions that would conflict.

**Comment by jlapeyre** [comment]
> but it's explicitly against the text of the spec

I see it.

It seems to me that it could be useful for many architectures and simulators to make the resources explicit.  Maybe I missed it, but I don't find this extension documented anywhere.

**Comment by jlapeyre** [comment]
At any rate, this is not a bug, but rather documented behavior.

**Comment by taalexander** [comment]
I've created #417 as there has also been other related discussion internally.

**Comment by jlapeyre** [comment]
@jakelishman wrote

>  ... allows this as a language extension, but it's explicitly against the text of the spec.

If a language extension is allowed to transgress a prohibition in the spec, then you can make extensions to make the language into anything you like.

(This issue is off topic here.)

**Comment by steleman** [comment]
> If a language extension is allowed to transgress a prohibition in the spec, then you can make extensions to make the language into anything you like.

https://github.com/openqasm/openqasm/pull/417
