### ISSUE TITLE
[forStatement] ANTLR reference grammar is incorrect

### ISSUE THREAD

**Issue by nelimee** [openqasm/openqasm#462]
## The issue

In [qasm3Parser.g4#L66](https://github.com/openqasm/openqasm/blob/05c0f9fd5211de972d55c8e4396f88cc251fa777/source/grammar/qasm3Parser.g4#L66)
```antlr
forStatement: FOR scalarType Identifier IN (setExpression | LBRACKET rangeExpression RBRACKET | Identifier) body=statementOrScope;
```
the grammar state that the iterable (i.e., the *thing* that will be iterated during the for-loop) is either:

- a `setExpression`
- a `rangeExpression`
- an `Identifier`

whereas the [official documentation on for-loop](https://openqasm.com/language/classical.html#for-loops) explicitly states that using `indexedIdentifier`s should be allowed:
> It is valid to use an indexing expression (e.g. my_array[1:3]) to arrive at one of the types given above.

## How to fix this

Replace `Identifier` by `indexedIdentifier` in the `forStatement` rule.

**Comment by jakelishman** [comment]
`indexedIdentifier` in the ANTLR grammar is a shorthand in the grammar for making certain l-value expressions clearer, whereas this is an r-value expression.  I'm fine to change the grammar (and the corresponding parser), but the targets should probably change to `setExpression | LBRACKET rangeExpression RBRACKET | expression` instead and the parser should sort out the type safety (the current reference parser only produces an _untyped_ AST at the moment, so it doesn't actually do any type checking).

**Comment by nelimee** [comment]
I will make a PR for this in the near future then. I agree with the l-value/r-value argument here.
