### ISSUE TITLE
can not run for loop in qasm3 as document say

### ISSUE THREAD

**Issue by eeeeeeeason** [openqasm/openqasm#484]
### OpenQASM version:

3

### Python version:

Python 3.10.8

### Operating system:

ibm quantum lab

### What is the current behavior?

Hello, I am planning to introduce the new features of QASM 3 to my colleagues. The capabilities as described in the paper seem very powerful, and I appreciate the work done by the community. However, I've found that the for loop is not working as I expected. What should I do?

https://docs.quantum-computing.ibm.com/build/dynamic-circuits-basics-with-openqasm3
![image](https://github.com/openqasm/openqasm/assets/27959851/f911d33d-b5e0-411e-8a98-fa470d883f85)

### Steps to reproduce the problem

```
# ctrl example1
import qiskit.qasm3
# Use AerSimulator
from qiskit_aer import AerSimulator
from qiskit import transpile
from qiskit.visualization import plot_state_city
backend = AerSimulator()
program = """
OPENQASM 3;
include "stdgates.inc";

qubit[4] q;

for i in [0:3] {
  h q[i];
}
"""
circuit = qiskit.qasm3.loads(program)

# First we have to transpile the quantum circuit
# to the low-level QASM instructions used by the
# backend
qc_compiled = transpile(circuit, backend)

# Execute the circuit on the qasm simulator.
# We've set the number of repeats of the circuit
# to be 1024, which is the default.
job_sim = backend.run(qc_compiled, shots=1024)

# Grab the results from the job.
# result_sim = job_sim.result()

circuit.draw("mpl")




```
### What is the expected behavior?

run the task normally,

**Comment by jlapeyre** [comment]
Hi @eeeeeeeason . Thanks for the report. This issue is better raised in the Qiskit repo https://github.com/Qiskit/qiskit.

Also,
Screen shots in bug reports should be avoided.
Another tip: It's easy to get [syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) in your code blocks.

**Comment by eeeeeeeason** [comment]
Thanks, I found that the documents related to "for loop" have been taken down. I originally learned about qasm3 from the paper[https://arxiv.org/pdf/2104.14722.pdf], but I found that many functions cannot be implemented[https://docs.quantum-computing.ibm.com/build/feature-table]. 

Please tell me where should I go to find qasm3 that can interact with qiskit or other What about examples of running on software?

**Comment by jwoehr** [comment]
OpenQASM 3 is forward-looking in the rapidly changing field of NISQ and has not been fully implemented by any organization yet.
Amazon Braket has a public implementation of a large subset of OpenQASM 3 in their Quantum offerings.

**Comment by eeeeeeeason** [comment]
@jwoehr @jlapeyre thanks~
