### ISSUE TITLE
[proposal]: Clarify interpretation of physical qubits

### ISSUE THREAD

**Issue by laurencap** [openqasm/openqasm#486]
### What is the expected enhancement?

From the documentation (https://openqasm.com/language/types.html#physical-qubits):

> While program qubits can be named, hardware qubits are referenced only by the syntax $[NUM]. For an n qubit system, we have physical qubit references given by $0, $1, …, $n-1. These qubit types are used in lower parts of the compilation stack when emitting physical circuits. Physical qubits must not be declared and they are, as all the qubits, global variables.

At AWS, we accept OpenQASM programs in the service, and we allow users to submit programs with physical qubits. As a developer interpreting OpenQASM semantics for our customers, I have the following questions and proposals:

1. I propose that we relax the requirement that physical qubit indices must be consecutive. There are some quantum devices that are not labeled with consecutive indices, such as Rigetti's Aspen devices.
2. What is the definition of physical circuits?
    1. My proposal, and assumption for the remainder of this issue: A physical circuit only has operations which are natively executable by the device without further decomposition. This includes that multi-qubit operations can be natively executed directly on that set of qubits, without additional SWAPs or routing between disconnected qubits.
    2. The documentation states that physical qubits are needed for representing physical circuits. Can physical qubits also appear beyond physical circuits? If the answer is no, that implies that the answer to the following questions — about mapping, routing, and non-native gates, respectively — is also no.
3. If a program is has physical qubits, can those qubits be remapped by a compiler? I presume no, or else virtual qubits would be more appropriate.
4. Can a two-qubit operation be applied to two qubits that aren’t directly connected? In other words, can routing be done for a program with physical qubits? I expect this to be valid OpenQASM code, but ultimately up to the compiler / hardware provider whether to accept it.
    1. For example, `CNOT $0, $2;` can be realized on a device with topology `0 <-> 1 <-> 2` by routing: `SWAP $1, $2; CNOT $0, $1; SWAP $1, $2;`
5. Can physical qubits be used with non-native gates? I expect this to also be valid, but again left to the discretion of the hardware provider whether to accept it.
    1. For example, `H $0`; can be realized on a device with a basis gate set of `{RX(pi/2), RZ(theta)}` by compiling to `RZ(0.5*pi) $0; RX(0.5*pi) $0; RZ(0.5*pi) $0;`

**Comment by laurencap** [comment]
Follow up AI: I will open a PR implementing my proposal taking into account feedback from today's meeting.

Notes from TSC:
- What are valid physical identifiers?
- Can physical qubits be a proper type?
- Physical circuit: only references physical qubits and gates that have a `defcal`
- What is meant by an executable / fully compiled program (with respect to a QPU)?
- What happens if there's a mix of physical and virtual qubits? I propose we limit scope to circuits that have all physical qubits, and no virtual qubits.
- Blake:
   - 3 is up to the compiler / user, not the language.
   - 4: definitely yes. Lev: in some cases this should be an error. Seems like it requires additional context from the user.

**Comment by jlapeyre** [comment]
Here are a few thoughts

#### 3
The spec should probably address the question in some way
a. The compiler is not allowed to remap physical qubits.
b. The compiler is allowed to remap physical qubits.
c. The compiler must provide an option to not remap physical qubits.

(a) seems a bit restrictive. But, following @laurencap 's comment, is there any semantic difference between on one hand doing a search and replace `$n` to `qn` and then letting the compiler choose a mapping to hardware qubits. And on the other hand allowing the compiler to remap already specified hardware qubits?

If (b) is chosen I can imagine a user being frustrated that a particular fully compliant OQ3 compiler will not respect their mapping choice. 

My preference from most to least preferred is c, a, b. Languages that are defined by an implementation often have documented optional behavior like this. I'm not so sure about languages that are instead defined by a spec. In the latter case, we may want to define a pragma for this. But OQ3 designers have not yet waded into specific pragmas. It would be something like `pragma no_remap`.

#### Mixed virtual and physical qubits

Is it possible that a user is not satisfied with the mapping done by the compiler? The user then wants to fix a subset of the mapping and then allow the compiler to do the rest of the mapping.

We could
a. Forbid mixing virtual qubits. And consider relaxing this if users/implementers present a reasonable use case, such as the one above.
b. Specify that language implementers may optionally support mixing them.
c. Specify that the language allows mixing. Then some compilers (probably all of them at the moment) would be non-compliant.

I'm leaning towards (b). On the other hand, it's not much different from compilers advertising that they don't support mixing, and so they are technically non-compliant.  It seems like (a) and (b) are changeable decisions, moreso (a). Whereas restricting (c) latter would not be backwards compatible.

**Comment by laurencap** [comment]
Resolved by #505
