### ISSUE TITLE
Clarify relationship between `bit`, `bit[1]` and `bool`

### ISSUE THREAD

**Issue by jakelishman** [openqasm/openqasm#535]
### What is the expected enhancement?

This stems from discussions we've had before, but was mostly triggered by an issue on Qiskit (Qiskit/qiskit#11870) that I forgot to bring over here between me and Blake, so I'll mostly just copy over the comments from that.

The original context is that Qiskit's legacy OQ3 importer rejected a program
```qasm
bit[4] c;
if (c[0] == "1") {
}
```
or the like, where `c[0]` (which I wrote the legacy importer to type as `bit`) is compared to `"0"` (which I typed `bit[1]`).  This is very related to #534.

**Comment by jakelishman** [comment]
Jake:

I think this is unclear on whether it ought to be permitted from the OQ3 spec. Personally I'd argue that `c[0] == "1"` isn't necessarily valid; I'd say `c[0]` has type `bit` or `bool` while `"1"` has type `bit[1]`, and my view is that those are semantically different types (and we never really did clarify whether `bit` and `bool` are the same).  The way I wrote parser at the time does that - it'll accept `c == "01"` as a valid comparison in the equality but not `c[0] == "1"` because it treats `"1"` as a `bit[1]` and says there's no implicit casting rule between `bit`/`bool` and `bit[1]`.

I'm happy enough to update that legacy backing parser to allow that, but I think we should clarify the OQ3 spec one way or the other on it.

Fwiw, my spec justification is these components:

> The classical types are divided into the ‘standard’ classical types (bool, int, uint, float, and complex) that exist in languages like C, and the ‘special’ classical types (bit, angle, duration, and stretch) that do not.

so there's no implicit conversion from `bool`-likes to `bit`, but an explicit cast of `bool` to `bit[1]` is allowed.

> Standard and special classical types may only mix in expressions with operators defined for those mixed types, otherwise explicit casts must be provided, unless otherwise noted (such as for assigning float values or expressions to angles).

Since there's no explicit allowance for `==` between `bit` and `bit[1]` (or `bool` and `bit[1]`), this semantic analysis forbids it.

**Comment by levbishop** [comment]
Per TSC 2024-05-15 meeting Jake is planning to turn the above proposal (`bit` scalar being a different type than `bit[1]`, that can behave equivalent to `bool`) into a full PR for later discussion.
