### ISSUE TITLE
Errors in the standard library documentation

### ISSUE THREAD

**Issue by projekter** [openqasm/openqasm#545]
### What is the file name(s) where you found the bug?

standard_library.rst

### What is the current text that needs to be fixed or removed? (You can copy and paste)

Definition of (at least) sdg (currently same as s) and rotation gates (currently 1/2 missing)

### What should the documentation say instead?

sdg: `i|1>` => `-i|1>`; rx/ry/rz/controlled: `theta` => `theta/2` (according to their definition in the paper in terms of `U`)

**Comment by jlapeyre** [comment]
Thanks, @projekter !
